<a href="https://colab.research.google.com/github/bedule/Desain-dan-Analisis-Algoritma/blob/main/M3_IMK_BELAJAR_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
aList = ["jore", 40, "nabiel", True, 3.14, 31.4]

In [2]:
print(aList)

['jore', 40, 'nabiel', True, 3.14, 31.4]


In [3]:
listMahasiswa = ("Abdul_Haris", 2021071001, "Informatika", "Desain_dan_Analisis_Algoritma", "14-9-2022", "UPJ")

In [4]:
print(listMahasiswa)

('Abdul_Haris', 2021071001, 'Informatika', 'Desain_dan_Analisis_Algoritma', '14-9-2022', 'UPJ')


Memanggil NIM dari list mahasiswa di atas

In [5]:
listMahasiswa[1]

2021071001

Memanggil Univesitas dari list mahasiswa di atas

In [6]:
listMahasiswa[5]

'UPJ'

Mencetak NIM dan Prodi menggunakan slicing, yaitu [1:3]

In [7]:
listMahasiswa[1:3]

(2021071001, 'Informatika')

Dalam soal di bawah memakai array, yang dimana index pertama itu dimulai dari 0. maka jika kita pilih 2 keluarnya akan 'BLUE'

In [8]:
bin_colors = ['RED', 'GREEN', 'BLUE', 'YELLOW']
bin_colors[2]

'BLUE'

Kalo misalnya mau ngambil banyak warna, maka harus mencetak [0:4]. 0 itu dihitung dari index 0,1,2,3. kalo misalnya 4 itu jumlah warnanya dimulai dari 1= RED

In [9]:
bin_colors = ['RED', 'GREEN', 'BLUE', 'YELLOW']
bin_colors[0:4]

['RED', 'GREEN', 'BLUE', 'YELLOW']

Iterasi adalah array yang sudah di tentukan + dengan keterangan yang kita mau. Dengan menggunakan for loop. CONTOH = array bersikan warna red, dll + square(kotak). maka outputnya akan keluar = RED SQUARE(KOTAK MERAH).

In [10]:
bin_colors = ['RED', 'GREEN', 'BLUE', 'YELLOW']
for coloring in bin_colors:
  print(coloring + " SQUARE")

RED SQUARE
GREEN SQUARE
BLUE SQUARE
YELLOW SQUARE


In [11]:
for mhs in listMahasiswa:
  print("UPJ",mhs)

UPJ Abdul_Haris
UPJ 2021071001
UPJ Informatika
UPJ Desain_dan_Analisis_Algoritma
UPJ 14-9-2022
UPJ UPJ


TUPLES adalah struktur data yang tidak bisa di ubah. CONTOH = Jika kita mau memanggil semua warna maka dimulai dari RED[0], maka kalian harus membuat [0:]. tanda ":" itu berguna untuk mengeluarkan sisa dari array

In [12]:
bin_colors = ('RED', 'GREEN', 'BLUE', 'YELLOW')
bin_colors[1]

'GREEN'

In [13]:
bin_colors[0:]

('RED', 'GREEN', 'BLUE', 'YELLOW')

In [14]:
UPJ = ('Univerisitas', 'Pembangunan', 'Jaya')
UPJ[0:]

('Univerisitas', 'Pembangunan', 'Jaya')

In [15]:
nested_tuple =(100, (200, 400, 600), (300), (400, 800))
nested_tuple[0:]

(100, (200, 400, 600), 300, (400, 800))

DICTIONARY mendefinisikan variable dengan warna atau KEY

In [16]:
bin_colors = {
    "manual_colors" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [17]:
bin_colors.get('approved_color')

'Green'

In [18]:
bin_colors['refused_color']

'Red'

In [19]:
bin_colors['approved_color'] = "PURPLE"
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'PURPLE', 'refused_color': 'Red'}


In [20]:
bin_mhs = {
    "mhs_nama" : "Abdul_Haris",
    "mhs_NIM" : "2021071001",
    "mhs_prodi" : "INFORMATIKA",
    "mhs_kampus" : "UPJ"
}
print(bin_mhs)

{'mhs_nama': 'Abdul_Haris', 'mhs_NIM': '2021071001', 'mhs_prodi': 'INFORMATIKA', 'mhs_kampus': 'UPJ'}


SETS Python, jika memasukan elemen yang sama maka akan di hitung hanya 1 saja

In [21]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [22]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'grass', 'leaves'}


In [23]:
yellow = {'dandelions', 'leaves','fire hydrants', 'rose'}
red = {'fire hydrants', 'blood', 'rose'}
print (yellow|red)
print (yellow&red)

{'dandelions', 'blood', 'fire hydrants', 'rose', 'leaves'}
{'rose', 'fire hydrants'}


In [24]:
import pandas as pd
import numpy as np

python DataFrame

In [25]:
df = pd.DataFrame ([
    ['1', 'abdul', 32, True], 
    ['2', 'jore', 23, False], 
    ['3', 'panjul', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
df


id    name  age  decision
0  1   abdul   32      True
1  2    jore   23     False
2  3  panjul   40      True

cara penulisan:
df.columns = ['id','name','age','decision']

In [26]:
df[['name', 'age']]

name  age
0   abdul   32
1    jore   23
2  panjul   40

In [27]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [28]:
df.iloc[1:3,:]

id    name  age  decision
1  2    jore   23     False
2  3  panjul   40      True

In [29]:
df[df.age>30]

id    name  age  decision
0  1   abdul   32      True
2  3  panjul   40      True

In [30]:
df[(df.age<35)&(df.decision == True)]

id   name  age  decision
0  1  abdul   32      True

In [31]:
df = pd.DataFrame ([
    ['1', 'Informatika', 50, 30, 20], 
    ['2', 'Sistem Informasi', 55, 30, 20], 
    ['3', 'Teknik sipil', 40, 30, 25]])
df.columns = ['NO', 'PRODI', 'MAHASISWA', 'LAKI LAKI', 'PEREMPUAN']
df

NO             PRODI  MAHASISWA  LAKI LAKI  PEREMPUAN
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         20
2  3      Teknik sipil         40         30         25

python MATRIX

In [32]:
myMatrix = np.array([[11,12,13], [21,22,23], [31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [33]:
myMatrix = np.array([[100,200,300], [700,600,500], [900,1000,800]])
print(myMatrix)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]


Python VEKTOR

In [35]:
myVector = [22,33,44,55]
print(myVector)


[22, 33, 44, 55]


**SLIDE 32**

In [36]:
print(type(myVector))

<class 'list'>


In [38]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [39]:
print(type(myVector))

<class 'numpy.ndarray'>
